---
- name: Prepare the environment
  hosts: swarm
  gather_facts: true
  become: true
  roles:
    - { role: prereq, tags: prereq }
    - { role: docker, tags: docker }

- name: Docker Swarm
  hosts: swarm
  become: true
  roles:
    - { role: cluster, tags: cluster }
    - { role: postreq/share, tags: share, when: share_enable | bool }

- name: Management deployments
  hosts: manager[0]
  become: true
  roles:
    - { role: stacks/mgmt, tags: mgmt }

- name: Log rotate
  hosts: manager
  become: true
  vars_files:
    - roles/docker/defaults/main.yml
  roles:
    - { role: postreq/logortate, tags: logortate }
